# =========================
# Build stage
# =========================
FROM maven:3.8.5-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B package -DskipTests

# =========================
# Run stage
# =========================
FROM eclipse-temurin:17-jre
WORKDIR /app

# (optionnel) outils utiles pour debug / Vault / healthcheck
RUN apt-get update \
 && apt-get install -y curl jq \
 && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

# Démarrage direct de Spring Boot
# Option 1️⃣ — Simple ENTRYPOINT (No JVM tuning)
#  ENTRYPOINT ["java", "-jar", "app.jar"]
# Option 2️⃣ — ENTRYPOINT with JAVA_OPTS (JVM tuning support)
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
