# Show the Role ID 
output "role_id" {
  value = vault_approle_auth_backend_role.web_app.role_id
}

# Show the Secret ID
# NOTE: This one is not used in the pipeline, it is generated by the pipeline
output "secret_id" {
  value = vault_approle_auth_backend_role_secret_id.id.secret_id
  sensitive = true
}